code --install-extension alefragnani.project-manager
code --install-extension amodio.toggle-excluded-files
code --install-extension andrewrazumovsky.vscode-styled-jsx-languageserver
code --install-extension andys8.jest-snippets
code --install-extension angular.ng-template
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eliostruyf.vscode-typescript-exportallmodules
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension firsttris.vscode-jest-runner
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-execution
code --install-extension graphql.vscode-graphql-syntax
code --install-extension green-csv.img-contextual
code --install-extension infeng.vscode-react-typescript
code --install-extension johnpapa.vscode-peacock
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kamikillerto.vscode-colorize
code --install-extension manuelalabor.rxjs-debugging-for-vs-code
code --install-extension mechatroner.rainbow-csv
code --install-extension meganrogge.template-string-converter
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension ms-playwright.playwright
code --install-extension ms-vscode.node-debug2
code --install-extension ms-vscode.powershell
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension n23.vscode-stylesheet-beautify
code --install-extension nrwl.angular-console
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension steoates.autoimport
code --install-extension tobermory.es6-string-html
code --install-extension tyriar.sort-lines
code --install-extension tyriar.vscode-terminal-here
code --install-extension usernamehw.errorlens
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension wallabyjs.console-ninja
code --install-extension withfig.fig
code --install-extension xaver.clang-format
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
code --install-extension zainchen.json